### ISSUE TITLE
The script oci-image-cleanup needs to remove /root/.ssh/authorized_keys

### ISSUE THREAD

**Issue by andytael** [oracle/oci-utils#79]
The script oci-image-cleanup needs to remove /root/.ssh/authorized_keys. 

Currently it doesn’t if the /etc/passwd is not containing /bin/bash or /bin/sh. Probably /bin/csh needs to be added too. In my case the value is /sbin/nologin I think

**Comment by ejannett** [comment]
Hi,
The check should be replaced by "all that de no have nologin as shell and <home>/.ssh "

**Comment by ejannett** [comment]
fixed
